name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # corre todos os dias à meia-noite
  workflow_dispatch:     # permite correr manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar Snake
        uses: Platane/snk@v3
        with:
          github_user_name: GabrielLima00
          outputs: |
            dist/snake.svg
            dist/snake.gif

      - name: Publicar no branch "output"
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
